server:
  port: 8761
eureka:
  renewal-percent-threshold: 0.85
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka-server

logging:
  level:
    root: TRACE