server:
  port: ${BACKEND_APP_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${BACKEND_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${BACKEND_OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "${BACKEND_OAUTH2_CALLBACK_URI}/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: ${BACKEND_OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${BACKEND_OAUTH2_FACEBOOK_CLIENT_SECRET}
            redirect-uri: "${BACKEND_OAUTH2_CALLBACK_URI}/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            client-id: ${BACKEND_OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${BACKEND_OAUTH2_GITHUB_CLIENT_SECRET}
            redirect-uri: "${BACKEND_OAUTH2_CALLBACK_URI}/{registrationId}"
            scope:
              - user:email
              - read:user

logging:
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.springframework.security: trace