server:
  port: 8050

spring:
  application:
    name: companies
  datasource:
    url: jdbc:postgresql://localhost:54321/projectmanagerdb
    username: devuser
    password: devpassword
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 1000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://devadmin:devpassword@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info
#    org.springframework.web: trace
#    org.hibernate: trace
#    org.hibernate.type.descriptor.sql: trace
#    org.springframework.transaction: trace
#    org.springframework.security: trace
#    org.springframework.mail: trace